title       = "mastodon"
baseURL     = "https://mastodon-cli.tamnd.com/"
description = "A command line for mastodon."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/mastodon-cli"
